# Generated by Django 4.2.29 on 2026-03-22 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Telegram chat ID used for direct bot messages.', max_length=64, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, help_text='Telegram user ID from inbound bot updates.', null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username captured from inbound updates.', max_length=255)),
                ('telegram_first_name', models.CharField(blank=True, max_length=255)),
                ('telegram_last_name', models.CharField(blank=True, max_length=255)),
                ('chat_type', models.CharField(default='private', help_text='Telegram chat type, usually private for direct inbox messaging.', max_length=32)),
                ('is_verified', models.BooleanField(default=False, help_text='Marks whether the Telegram connection has been verified by a webhook update.')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('last_webhook_update_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notification_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Notification Connection',
                'verbose_name_plural': 'Telegram Notification Connections',
            },
        ),
        migrations.CreateModel(
            name='TelegramWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('update_id', models.BigIntegerField(help_text='Telegram update_id for idempotent webhook processing.', unique=True)),
                ('event_type', models.CharField(choices=[('message', 'Message'), ('callback_query', 'Callback Query'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='notifications.telegramnotificationconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_webhook_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Webhook Event',
                'verbose_name_plural': 'Telegram Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
