# Generated by Django 4.2.29 on 2026-03-22 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_telegram_notification_data(apps, schema_editor):
    TelegramNotificationConnection = apps.get_model("notifications", "TelegramNotificationConnection")
    TelegramWebhookEvent = apps.get_model("notifications", "TelegramWebhookEvent")
    NotificationConnection = apps.get_model("notifications", "NotificationConnection")
    NotificationWebhookEvent = apps.get_model("notifications", "NotificationWebhookEvent")

    connection_id_map = {}

    for old_connection in TelegramNotificationConnection.objects.all():
        new_connection = NotificationConnection.objects.create(
            id=old_connection.id,
            created_at=old_connection.created_at,
            updated_at=old_connection.updated_at,
            is_active=old_connection.is_active,
            user_id=old_connection.user_id,
            platform="telegram",
            destination_type="chat",
            destination=old_connection.telegram_chat_id or "",
            external_user_id=str(old_connection.telegram_user_id or ""),
            external_channel_id=old_connection.telegram_chat_id or "",
            display_name=" ".join(
                part for part in [old_connection.telegram_first_name, old_connection.telegram_last_name] if part
            ).strip() or old_connection.telegram_username,
            metadata={
                "telegram_username": old_connection.telegram_username,
                "telegram_first_name": old_connection.telegram_first_name,
                "telegram_last_name": old_connection.telegram_last_name,
                "chat_type": old_connection.chat_type,
            },
            is_verified=old_connection.is_verified,
            is_primary=True,
            connected_at=old_connection.connected_at,
            last_interaction_at=old_connection.last_interaction_at,
            last_inbound_event_id=str(old_connection.last_webhook_update_id or ""),
        )
        connection_id_map[old_connection.id] = new_connection.id

    for old_event in TelegramWebhookEvent.objects.all():
        NotificationWebhookEvent.objects.create(
            id=old_event.id,
            created_at=old_event.created_at,
            updated_at=old_event.updated_at,
            is_active=old_event.is_active,
            connection_id=connection_id_map.get(old_event.connection_id),
            user_id=old_event.user_id,
            platform="telegram",
            event_type=old_event.event_type,
            direction="inbound",
            external_event_id=str(old_event.update_id or ""),
            destination=old_event.telegram_chat_id or "",
            external_user_id=str(old_event.telegram_user_id or ""),
            payload=old_event.payload,
            metadata={},
            processed=old_event.processed,
            processed_at=old_event.processed_at,
            error_message=old_event.error_message,
        )


def reverse_telegram_notification_data(apps, schema_editor):
    NotificationConnection = apps.get_model("notifications", "NotificationConnection")
    NotificationWebhookEvent = apps.get_model("notifications", "NotificationWebhookEvent")
    NotificationWebhookEvent.objects.filter(platform="telegram").delete()
    NotificationConnection.objects.filter(platform="telegram").delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push'), ('webhook', 'Webhook'), ('custom', 'Custom')], max_length=32)),
                ('destination_type', models.CharField(choices=[('chat', 'Chat'), ('email', 'Email'), ('phone', 'Phone'), ('webhook', 'Webhook'), ('device', 'Device'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('destination', models.CharField(help_text='The provider destination such as email, phone, chat id, or webhook URL.', max_length=255)),
                ('external_user_id', models.CharField(blank=True, help_text='Provider user identifier when available.', max_length=255)),
                ('external_channel_id', models.CharField(blank=True, help_text='Provider chat, room, or channel identifier when available.', max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific metadata stored without changing the schema.')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Only one active primary notification method is allowed per user.')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_event_id', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'platform', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push'), ('webhook', 'Webhook'), ('custom', 'Custom')], max_length=32)),
                ('notification_type', models.CharField(max_length=64)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('read', 'Read')], default='pending', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.notificationconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push'), ('webhook', 'Webhook'), ('custom', 'Custom')], max_length=32)),
                ('event_type', models.CharField(default='unknown', max_length=64)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=16)),
                ('external_event_id', models.CharField(blank=True, help_text='Provider event id used for deduplication when available.', max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('external_user_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='notifications.notificationconnection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_webhook_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            migrate_telegram_notification_data,
            reverse_telegram_notification_data,
        ),
        migrations.DeleteModel(
            name='TelegramNotificationConnection',
        ),
        migrations.DeleteModel(
            name='TelegramWebhookEvent',
        ),
        migrations.AddIndex(
            model_name='notificationwebhookevent',
            index=models.Index(fields=['platform', 'external_user_id'], name='notif_event_platform_user_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationwebhookevent',
            index=models.Index(fields=['platform', 'destination'], name='notif_event_platform_dest_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationwebhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('platform', 'external_event_id'), name='unique_notification_webhook_event_per_platform'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['user', 'status'], name='notif_delivery_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['platform', 'status'], name='notif_deliv_plat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationconnection',
            index=models.Index(fields=['user', 'platform'], name='notif_conn_user_platform_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationconnection',
            index=models.Index(fields=['platform', 'external_user_id'], name='notif_conn_platform_user_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationconnection',
            index=models.Index(fields=['platform', 'external_channel_id'], name='notif_conn_plat_chan_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationconnection',
            constraint=models.UniqueConstraint(fields=('user', 'platform', 'destination'), name='unique_notification_connection_per_destination'),
        ),
        migrations.AddConstraint(
            model_name='notificationconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('user',), name='unique_active_primary_notification_connection_per_user'),
        ),
    ]
