# Generated by Django 4.2.29 on 2026-03-22 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_notificationconnection_notificationdelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push'), ('webhook', 'Webhook'), ('custom', 'Custom')], max_length=32)),
                ('reference_id', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_connection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'platform'], name='notif_req_user_platform_idx'), models.Index(fields=['platform', 'reference_id'], name='notif_req_plat_ref_idx'), models.Index(fields=['expires_at'], name='notif_req_exp_idx')],
            },
        ),
    ]
