# Generated by Django 4.2.29 on 2026-04-16 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('facebook', 'Facebook')], max_length=50)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('id_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(default='', max_length=500)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider'], name='accounts_oa_user_id_6f1aed_idx'), models.Index(fields=['user', 'provider', 'is_active'], name='accounts_oa_user_id_c73d9e_idx')],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
