# Generated by Django 4.2.29 on 2026-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent_for_approval', 'Sent For Approval'), ('approved', 'Approved'), ('queued', 'Queued'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='draft', max_length=32),
        ),
    ]
